---
chains:
  - binary_name: noisd
    chain_id: nois-testnet-003
    denom: unois
    faucet: "http://faucet.noislabs.com"
    gas_price: 0.05
    ibc_connection:
      dest: ~
      src: ~
    name: nois-testnet-003
    prefix: nois
    rpc:
      - "https://rpc.noislabs.com:443"
    wasm:
      contracts:
        - address: nois1s9ly26evj8ehurptws5d6dm4a9g2z0htcqvlvn95kc30eucl4s5sd8hkgp
          code_id: "48"
          git_asset_name: nois_oracle
          instantiation_msg: '{"incentive_amount":"1000000","incentive_denom":"unois","min_round":TEMPLATE_MIN_ROUND}'
          name: nois-oracle
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.7.2
  - binary_name: fetchd #https://docs.fetch.ai/
    chain_id: dorado-1
    denom: atestfet
    faucet: ~ # use https://explore-dorado.fetch.ai/
    gas_price: 1000000000
    ibc_connection:
      dest: ~
      src: ~
      counterpart:
        chain: nois-testnet-003
        contract_name: nois-oracle
    name: dorado-1
    prefix: fetch
    rpc:
      - "https://rpc-dorado.fetch.ai:443"
    wasm:
      contracts:
        - address: "fetch1kmejslevu86amd3cjvy5n8lzsse687kuk2me3vg9tdcvmxwmw5kqedfk4r"
          code_id: "3818"
          git_asset_name: nois_proxy
          instantiation_msg: '{"prices":[{"denom":"TEMPLATE_DENOM","amount":"100"}],"withdrawal_address":"TEMPLATE_WITHDRAWAL_ADDRESS","test_mode":false}'
          name: nois-proxy
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.7.2
        - address: fetch17sy34g7hplahqhtkrrdwy3takd54uxe4ndkhwahex7k4a85chu7q5ddhmd
          code_id: "3819"
          git_asset_name: nois_demo
          instantiation_msg: '{"nois_proxy":"TEMPLATE_NOIS_PROXY"}'
          name: nois-demo
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.7.2
        - address: fetch1dmk8ne3xuknrchqcylnr5nvwtp3e3gum9aajyazhqjrlnaekxunq3k6hlg
          code_id: "3820"
          git_asset_name: double_dice_roll
          instantiation_msg: '{"nois_proxy":"TEMPLATE_NOIS_PROXY"}'
          name: double-dice-roll
          url: "https://github.com/noislabs/nois-dapp-examples"
          version: v0.4.3
  - binary_name: aurad
    chain_id: euphoria-1
    denom: ueaura
    faucet: ~
    gas_price: 0.04
    ibc_connection:
      dest: ~
      src: ~
      counterpart:
        chain: nois-testnet-003
        contract_name: nois-oracle
    name: euphoria-1
    prefix: aura
    rpc:
      - "https://rpc.euphoria.aura.network:443"
    wasm:
      contracts:
        - address: "null"
          code_id: "null"
          git_asset_name: nois_proxy
          instantiation_msg: '{"prices":[{"denom":"TEMPLATE_DENOM","amount":"100"}],"withdrawal_address":"TEMPLATE_WITHDRAWAL_ADDRESS","test_mode":false}'
          name: nois-proxy
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.7.2
        - address: "null"
          code_id: "null"
          git_asset_name: nois_demo
          instantiation_msg: '{"nois_proxy":"TEMPLATE_NOIS_PROXY"}'
          name: nois-demo
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.7.2
        - address: "null"
          code_id: "null"
          git_asset_name: double_dice_roll
          instantiation_msg: '{"nois_proxy":"TEMPLATE_NOIS_PROXY"}'
          name: double-dice-roll
          url: "https://github.com/noislabs/nois-dapp-examples"
          version: v0.4.3
  - binary_name: osmosisd
    chain_id: osmo-test-4
    denom: uosmo
    faucet: ~
    gas_price: 0.04
    ibc_connection:
      dest: ~
      src: ~
      counterpart:
        chain: nois-testnet-003
        contract_name: nois-oracle
    name: osmo-test-4
    prefix: osmo
    rpc:
      - "https://rpc-test.osmosis.zone:443"
    wasm:
      contracts:
        - address: osmo1t76rmvp59w4kguq55npyk34hm46ckv30t6zmcwve0qg6a3eswq3qrnqpml
          code_id: "3065"
          git_asset_name: nois_proxy
          instantiation_msg: '{"prices":[{"denom":"TEMPLATE_DENOM","amount":"100"}],"withdrawal_address":"TEMPLATE_WITHDRAWAL_ADDRESS","test_mode":false}'
          name: nois-proxy
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.7.2
        - address: osmo1fj7srfrn6fxcpe2ttt9x699qwqt962pcaene6dx059qx3c85pp3sr8l087
          code_id: "3066"
          git_asset_name: nois_demo
          instantiation_msg: '{"nois_proxy":"TEMPLATE_NOIS_PROXY"}'
          name: nois-demo
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.7.2
        - address: osmo1ryv9k5vax5j68kqq49pnkzg73pcr7pm5vc4jf8crd64x84pr7psqzp39jf
          code_id: "3067"
          git_asset_name: double_dice_roll
          instantiation_msg: '{"nois_proxy":"TEMPLATE_NOIS_PROXY"}'
          name: double-dice-roll
          url: "https://github.com/noislabs/nois-dapp-examples"
          version: v0.4.3
  - binary_name: starsd
    chain_id: elgafar-1
    denom: ustars
    faucet: ~
    gas_price: 0.025
    ibc_connection:
      dest: connection-10
      src: connection-18
      counterpart:
        chain: nois-testnet-003
        contract_name: nois-oracle
    name: elgafar-1
    prefix: stars
    rpc:
      - "https://rpc.elgafar-1.stargaze-apis.com:443"
    wasm:
      contracts:
        - address: stars1caqz4ye9uwm5mtqnyg6vtvqq2gkawlc95vn2c3ede3xxhsrk55fsggxw3u
          code_id: "292"
          git_asset_name: nois_proxy
          instantiation_msg: '{"prices":[{"denom":"TEMPLATE_DENOM","amount":"100"}],"withdrawal_address":"TEMPLATE_WITHDRAWAL_ADDRESS","test_mode":false}'
          name: nois-proxy
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.7.2
        - address: stars17xyyg02cul4nvlraf2sw99n8xdcjexr8xgznl3aftnrhtqp490ds990t4m
          code_id: "293"
          git_asset_name: nois_demo
          instantiation_msg: '{"nois_proxy":"TEMPLATE_NOIS_PROXY"}'
          name: nois-demo
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.7.2
        - address: stars1u62rtu66qeddpjsq50m7zv95gjfg20yz50fdja6s4rxe4qtnpstsv9dwng
          code_id: "294"
          git_asset_name: double_dice_roll
          instantiation_msg: '{"nois_proxy":"TEMPLATE_NOIS_PROXY"}'
          name: double-dice-roll
          url: "https://github.com/noislabs/nois-dapp-examples"
          version: v0.4.3
  - binary_name: junod
    chain_id: uni-5
    denom: ujunox
    faucet: "https://faucet.uni.juno.deuslabs.fi"
    gas_price: 0.025
    ibc_connection:
      dest: connection-12
      src: connection-39
      counterpart:
        chain: nois-testnet-003
        contract_name: nois-oracle
    name: uni-5
    prefix: juno
    rpc:
      - "https://rpc.uni.juno.deuslabs.fi:443"
    wasm:
      contracts:
        - address: "juno1tquqqdvlv3fwu5u6evpt7e4ss47zczug8tq4czjucgx8dulkhjxsegfuds"
          code_id: "1304"
          git_asset_name: nois_proxy
          instantiation_msg: '{"prices":[{"denom":"TEMPLATE_DENOM","amount":"100"}],"withdrawal_address":"TEMPLATE_WITHDRAWAL_ADDRESS","test_mode":false}'
          name: nois-proxy
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.7.2
        - address: "juno1e0hfn788fesr60n7g4gy4qc6mwmn99wt9mwk9v0gt4ch3q5kwr0s9shunj"
          code_id: "1305"
          git_asset_name: nois_demo
          instantiation_msg: '{"nois_proxy":"TEMPLATE_NOIS_PROXY"}'
          name: nois-demo
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.7.2
        - address: "juno1e7p6k4c0l52zperyhd6nfx053yrdgjw4k6kunszhk9j0smedgtzs27nrkh"
          code_id: "1306"
          git_asset_name: double_dice_roll
          instantiation_msg: '{"nois_proxy":"TEMPLATE_NOIS_PROXY"}'
          name: double-dice-roll
          url: "https://github.com/noislabs/nois-dapp-examples"
          version: v0.4.3
  - binary_name: junod
    chain_id: juno-1
    denom: ujuno
    faucet: ~
    gas_price: 0.0025
    ibc_connection:
      dest: connection-16
      src: connection-255
      counterpart:
        chain: nois-testnet-003
        contract_name: nois-oracle
    name: juno-1
    prefix: juno
    rpc:
      - "https://rpc-juno.mib.tech:443"
    wasm:
      contracts:
        - address: "juno13qw7myq026jesj5jutzzxmlfemc7468n8dp7vty7zlw8w08cyxuqfsvxh3"
          code_id: "1304"
          git_asset_name: nois_proxy
          instantiation_msg: '{"prices":[{"denom":"TEMPLATE_DENOM","amount":"500000"}],"withdrawal_address":"TEMPLATE_WITHDRAWAL_ADDRESS","test_mode":false}'
          name: nois-proxy
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.7.2
        - address: "juno1jzsm394v2gjah559ks0j3scj5lmk7dg29aj9e08gvtzlyhxwzrascpmlw7"
          code_id: "1456"
          git_asset_name: double_dice_roll
          instantiation_msg: '{"nois_proxy":"TEMPLATE_NOIS_PROXY"}'
          name: double-dice-roll
          url: "https://github.com/noislabs/nois-dapp-examples"
          version: v0.4.3
ibc:
  relayer:
    docker_image: noislabs/nois-relayer
  version: nois-v3
