---
chains:
  - binary_name: noisd
    chain_id: nois-testnet-004
    denom: unois
    faucet: "http://faucet.noislabs.com"
    gas_price: 0.05
    ibc_connection:
      dest: ~
      src: ~
    name: nois-testnet-004
    prefix: nois
    rpc:
      - "https://nois-004.rpc.bccnodes.com:443"
    wasm:
      contracts:
        - address: nois16peq3sftghumkja7nu32ztjy0ew4vsnshxfhcv6sxq573ta08gwsgldepm
          code_id: "11"
          git_asset_name: nois_drand
          instantiation_msg: '{"incentive_point_price":"25000","incentive_denom":"unois","min_round":TEMPLATE_MIN_ROUND,"manager":"nois1p9tw323xdjp5q3yzuecfahmgrpufmm89z93wpk"}'
          name: nois-drand
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.10.0
        - address: nois1ze9qajd25ucqnvn2u865uhdtjd6qm5awm3tpl93ure72wgs4d7qsptqc0u
          code_id: "12"
          git_asset_name: nois_gateway
          instantiation_msg: '{}'
          name: nois-gateway
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.10.0
        - address: nois1mdjzz7y7crnjgfkdld4x9ravqymh22jy2c7jpukqnkghhzv5s9ys2a9hu7
          code_id: "14"
          git_asset_name: nois_icecube
          instantiation_msg: '{"manager":"nois1p9tw323xdjp5q3yzuecfahmgrpufmm89z93wpk"}'
          name: nois-icecube
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.10.0
        - address: nois16rpxzry8jf06j8htjphf0lnmylh28enwm4xwkfpn3699wvyys2yqgcev3h
          code_id: "13"
          git_asset_name: nois_sink
          instantiation_msg: '{}'
          name: nois-sink
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.10.0
  - binary_name: aurad
    chain_id: euphoria-2
    denom: ueaura
    faucet: ~
    gas_price: 0.04
    ibc_connection:
      dest: ~
      src: ~
      counterpart:
        chain: nois-testnet-004
        contract_name: nois-gateway
    name: euphoria-2
    prefix: aura
    rpc:
      - "https://rpc.euphoria.aura.network:443"
    wasm:
      contracts:
        - address:
          code_id:
          git_asset_name: nois_proxy
          instantiation_msg: '{"prices":[{"denom":"TEMPLATE_DENOM","amount":"100"}],"withdrawal_address":"TEMPLATE_WITHDRAWAL_ADDRESS","callback_gas_limit":500000,"test_mode":false}'
          name: nois-proxy
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.10.0
        - address:
          code_id:
          git_asset_name: nois_demo
          instantiation_msg: '{"nois_proxy":"TEMPLATE_NOIS_PROXY"}'
          name: nois-demo
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.10.0
        - address:
          code_id:
          git_asset_name: double_dice_roll
          instantiation_msg: '{"nois_proxy":"TEMPLATE_NOIS_PROXY"}'
          name: double-dice-roll
          url: "https://github.com/noislabs/nois-dapp-examples"
          version: v0.5.0
  - binary_name: starsd
    chain_id: elgafar-1
    denom: ustars
    faucet: ~
    gas_price: 0.025
    ibc_connection:
      dest: ~
      src: ~
      counterpart:
        chain: nois-testnet-004
        contract_name: nois-gateway
    name: elgafar-1
    prefix: stars
    rpc:
      - "https://rpc.elgafar-1.stargaze-apis.com:443"
    wasm:
      contracts:
        - address:
          code_id: "1627"
          git_asset_name: nois_proxy
          instantiation_msg: '{"prices":[{"denom":"TEMPLATE_DENOM","amount":"100"}],"withdrawal_address":"TEMPLATE_WITHDRAWAL_ADDRESS","callback_gas_limit":500000,"test_mode":false}'
          name: nois-proxy
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.10.0
        - address:
          code_id:
          git_asset_name: nois_demo
          instantiation_msg: '{"nois_proxy":"TEMPLATE_NOIS_PROXY"}'
          name: nois-demo
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.10.0
        - address:
          code_id:
          git_asset_name: double_dice_roll
          instantiation_msg: '{"nois_proxy":"TEMPLATE_NOIS_PROXY"}'
          name: double-dice-roll
          url: "https://github.com/noislabs/nois-dapp-examples"
          version: v0.5.0
  - binary_name: junod
    chain_id: uni-6
    denom: ujunox
    faucet: "https://faucet.uni.juno.deuslabs.fi"
    gas_price: 0.025
    ibc_connection:
      dest: ~
      src: ~
      counterpart:
        chain: nois-testnet-004
        contract_name: nois-gateway
    name: uni-6
    prefix: juno
    rpc:
      - "https://rpc.uni.junonetwork.io:443"
    wasm:
      contracts:
        - address:
          code_id:
          git_asset_name: nois_proxy
          instantiation_msg: '{"prices":[{"denom":"TEMPLATE_DENOM","amount":"100"}],"withdrawal_address":"TEMPLATE_WITHDRAWAL_ADDRESS","callback_gas_limit":500000,"test_mode":false}'
          name: nois-proxy
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.10.0
        - address:
          code_id:
          git_asset_name: nois_demo
          instantiation_msg: '{"nois_proxy":"TEMPLATE_NOIS_PROXY"}'
          name: nois-demo
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.10.0
        - address:
          code_id:
          git_asset_name: double_dice_roll
          instantiation_msg: '{"nois_proxy":"TEMPLATE_NOIS_PROXY"}'
          name: double-dice-roll
          url: "https://github.com/noislabs/nois-dapp-examples"
          version: v0.5.0
  - binary_name: juno1d
    chain_id: juno-1
    denom: ujuno
    faucet: ~
    gas_price: 0.0025
    ibc_connection:
      dest: ~
      src: ~
      counterpart:
        chain: nois-testnet-004
        contract_name: nois-gateway
    name: juno-1
    prefix: juno
    rpc:
      - "https://rpc-juno.mib.tech:443"
    wasm:
      contracts:
        - address:
          code_id:
          git_asset_name: nois_proxy
          instantiation_msg: '{"prices":[{"denom":"TEMPLATE_DENOM","amount":500000}],"withdrawal_address":"TEMPLATE_WITHDRAWAL_ADDRESS","callback_gas_limit":500000,"test_mode":false}'
          name: nois-proxy
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.10.0
        - address:
          code_id:
          git_asset_name: double_dice_roll
          instantiation_msg: '{"nois_proxy":"TEMPLATE_NOIS_PROXY"}'
          name: double-dice-roll
          url: "https://github.com/noislabs/nois-dapp-examples"
          version: v0.5.0
ibc:
  relayer:
    docker_image: noislabs/nois-relayer
  version: nois-v5
