---
chains:
  - binary_name: noisd
    chain_id: nois-1
    denom: unois
    faucet: ~
    gas_price: 0.05
    ibc_connection:
      dest: ~
      src: ~
    name: nois-1
    prefix: nois
    rpc:
      - https://nois-mainnet-rpc.bccnodes.com:443
    wasm:
      contracts:
        - address: nois19w26q6n44xqepduudfz2xls4pc5lltpn6rxu34g0jshxu3rdujzsj7dgu8
          code_id: "4"
          git_asset_name: nois_drand
          instantiation_msg: '{"incentive_point_price":"3000","incentive_denom":"unois","min_round":TEMPLATE_MIN_ROUND,"manager":"nois1p9tw323xdjp5q3yzuecfahmgrpufmm89z93wpk"}'
          name: nois-drand
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.11.0
        - address: nois10c0ppz0n57hqrmfp7g7lqs6k4xk9rxhvcfkqt83r8mars2lc57mq0f6cty
          code_id: "5"
          git_asset_name: nois_sink
          instantiation_msg: '{}'
          name: nois-sink
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.11.0
        - address: nois1gwnfyx82rwgc4y9r8vx6nr9v35dwezw3dadw6h39mad9amg7shnsler5f0
          code_id: "6"
          git_asset_name: nois_icecube
          instantiation_msg: '{"manager":"nois1p9tw323xdjp5q3yzuecfahmgrpufmm89z93wpk"}'
          name: nois-icecube
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.11.0
          #- address:
          #  code_id:
          #  git_asset_name: nois_payment
          #  instantiation_msg: '{}'
          #  name: nois-payment
          #  url: "https://github.com/noislabs/nois-contracts"
          #  version: v0.11.0
          #- address:
          #  code_id:
          #  git_asset_name: nois_gateway
          #  instantiation_msg: '{"manager":"nois1p9tw323xdjp5q3yzuecfahmgrpufmm89z93wpk","price":{"denom":"TEMPLATE_DENOM","amount":"50000000"},"payment_code_id":"TEMPLATE_PAYMENT_CODE_ID","sink":"TEMPLATE_SINK_ADDR"}'
          #  name: nois-gateway
          #  url: "https://github.com/noislabs/nois-contracts"
          #  version: v0.11.0
  - binary_name: noisd
    chain_id: nois-testnet-005
    denom: unois
    faucet: "http://faucet.noislabs.com"
    gas_price: 0.05
    ibc_connection:
      dest: ~
      src: ~
    name: nois-testnet-005
    prefix: nois
    rpc:
      - "https://nois-testnet-rpc.polkachu.com:443"
    wasm:
      contracts:
        - address: nois14xef285hz5cx5q9hh32p9nztu3cct4g44sxjgx3dmftt2tj2rweqkjextk
          code_id: "1"
          git_asset_name: nois_drand
          instantiation_msg: '{"incentive_point_price":"3000","incentive_denom":"unois","min_round":TEMPLATE_MIN_ROUND,"manager":"nois1tfg9ptr84t9zshxxf5lkvrd6ej7gxjh75lztve"}'
          name: nois-drand
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.11.0
        - address: nois10c0ppz0n57hqrmfp7g7lqs6k4xk9rxhvcfkqt83r8mars2lc57mq0f6cty
          code_id: "5"
          git_asset_name: nois_sink
          instantiation_msg: '{}'
          name: nois-sink
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.11.0
        - address: This_contract_is_not_meant_to_be_deployed_by_the_script
          code_id: "15"
          git_asset_name: nois_payment
          instantiation_msg: '{}'
          name: nois-payment
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.11.0
        - address: "nois1x55xhexprdwfl6nfju53hfxj77nsxlj5c9jzyvjuastl9f3dt6jsx6l9yg"
          code_id: "10"
          git_asset_name: nois_gateway
          instantiation_msg: '{"manager":"nois1tfg9ptr84t9zshxxf5lkvrd6ej7gxjh75lztve","price":{"denom":"TEMPLATE_DENOM","amount":"50000000"}}'
          name: nois-gateway
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.11.0
        - address: nois1gwnfyx82rwgc4y9r8vx6nr9v35dwezw3dadw6h39mad9amg7shnsler5f0
          code_id: "6"
          git_asset_name: nois_icecube
          instantiation_msg: '{"manager":"nois1tfg9ptr84t9zshxxf5lkvrd6ej7gxjh75lztve"}'
          name: nois-icecube
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.11.0
  - binary_name: aurad
    chain_id: euphoria-2
    denom: ueaura
    faucet: ~
    gas_price: 0.04
    ibc_connection:
      dest: connection-2
      src: connection-55
      counterpart:
        chain: nois-testnet-005
        contract_name: nois-gateway
    name: euphoria-2
    prefix: aura
    rpc:
      - "https://rpc.euphoria.aura.network:443"
    wasm:
      contracts:
        - address: aura1rraqed5ew59r9ntzqssvmtvtz3uxa6qrvxjs020vyt5vnyszdhtslasrzf
          code_id: "720"
          git_asset_name: nois_proxy
          instantiation_msg: '{"prices":[{"denom":"TEMPLATE_DENOM","amount":"100"}],"withdrawal_address":"TEMPLATE_WITHDRAWAL_ADDRESS","callback_gas_limit":500000,"test_mode":false}'
          name: nois-proxy
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.11.0
        - address: aura1434cv3hxmguj497az9qv26esyhwrwurkejepjgxf05lpwn9vc2gq6sej55
          code_id: "721"
          git_asset_name: nois_demo
          instantiation_msg: '{"nois_proxy":"TEMPLATE_NOIS_PROXY"}'
          name: nois-demo
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.11.0
        - address: aura1t78dz0mene6dpmn3ldnhtl9hmxqmwm2re0z9p0a4865ndd2agvzq0dsahc
          code_id: "722"
          git_asset_name: double_dice_roll
          instantiation_msg: '{"nois_proxy":"TEMPLATE_NOIS_PROXY"}'
          name: double-dice-roll
          url: "https://github.com/noislabs/nois-dapp-examples"
          version: v0.5.1
  - binary_name: starsd
    chain_id: elgafar-1
    denom: ustars
    faucet: ~
    gas_price: 0.025
    ibc_connection:
      dest: ~
      src: ~
      counterpart:
        chain: nois-testnet-005
        contract_name: nois-gateway
    name: elgafar-1
    prefix: stars
    rpc:
      - "https://rpc.elgafar-1.stargaze-apis.com:443"
    wasm:
      contracts:
        - address:
          code_id: "1627"
          git_asset_name: nois_proxy
          instantiation_msg: '{"prices":[{"denom":"TEMPLATE_DENOM","amount":"100"}],"withdrawal_address":"TEMPLATE_WITHDRAWAL_ADDRESS","callback_gas_limit":500000,"test_mode":false}'
          name: nois-proxy
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.11.0
        - address:
          code_id:
          git_asset_name: nois_demo
          instantiation_msg: '{"nois_proxy":"TEMPLATE_NOIS_PROXY"}'
          name: nois-demo
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.11.0
        - address:
          code_id:
          git_asset_name: double_dice_roll
          instantiation_msg: '{"nois_proxy":"TEMPLATE_NOIS_PROXY"}'
          name: double-dice-roll
          url: "https://github.com/noislabs/nois-dapp-examples"
          version: v0.5.1
  - binary_name: junod
    chain_id: uni-6
    denom: ujunox
    faucet: "https://faucet.uni.juno.deuslabs.fi"
    gas_price: 0.025
    ibc_connection:
      dest: connection-0
      src: connection-164
      counterpart:
        chain: nois-testnet-005
        contract_name: nois-gateway
    name: uni-6
    prefix: juno
    rpc:
      - "https://rpc.uni.junonetwork.io:443"
    wasm:
      contracts:
        - address: juno1ythyt9wm9y4yxlv8eqccs4p78tylky5q0yx8gfpwycq6ywlycces87e20q
          code_id: "1341"
          git_asset_name: nois_proxy
          instantiation_msg: '{"prices":[{"denom":"TEMPLATE_DENOM","amount":"100"}],"withdrawal_address":"TEMPLATE_WITHDRAWAL_ADDRESS","callback_gas_limit":500000,"test_mode":false}'
          name: nois-proxy
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.11.0
        - address: juno1uw8w93vyvmxmgalrskcc6jmh6txvej2hlhwtyy84vw4w2c6cl92qcssf68
          code_id: "1342"
          git_asset_name: nois_demo
          instantiation_msg: '{"nois_proxy":"TEMPLATE_NOIS_PROXY"}'
          name: nois-demo
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.11.0
        - address: juno1d6dk3s6sw5k8z2mcjkesjgrazu3c2maz3nwd7hq7628g03pputqskxld6e
          code_id: "1343"
          git_asset_name: double_dice_roll
          instantiation_msg: '{"nois_proxy":"TEMPLATE_NOIS_PROXY"}'
          name: double-dice-roll
          url: "https://github.com/noislabs/nois-dapp-examples"
          version: v0.5.1
  - binary_name: juno1d
    chain_id: juno-1
    denom: ujuno
    faucet: ~
    gas_price: 0.0025
    ibc_connection:
      dest: ~
      src: ~
      counterpart:
        chain: nois-testnet-005
        contract_name: nois-gateway
    name: juno-1
    prefix: juno
    rpc:
      - "https://rpc-juno.mib.tech:443"
    wasm:
      contracts:
        - address:
          code_id:
          git_asset_name: nois_proxy
          instantiation_msg: '{"prices":[{"denom":"TEMPLATE_DENOM","amount":500000}],"withdrawal_address":"TEMPLATE_WITHDRAWAL_ADDRESS","callback_gas_limit":500000,"test_mode":false}'
          name: nois-proxy
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.11.0
        - address:
          code_id:
          git_asset_name: double_dice_roll
          instantiation_msg: '{"nois_proxy":"TEMPLATE_NOIS_PROXY"}'
          name: double-dice-roll
          url: "https://github.com/noislabs/nois-dapp-examples"
          version: v0.5.1
ibc:
  relayer:
    docker_image: noislabs/nois-relayer
  version: nois-v5
