---
chains:
  - binary_name: noisd
    chain_id: nois-testnet-003
    denom: unois
    faucet: "http://faucet.noislabs.com"
    gas_price: 0.05
    ibc_connection:
      dest: ~
      src: ~
    name: nois-testnet-003
    prefix: nois
    rpc:
      - "https://nois-testnet.nodejumper.io:443"
    wasm:
      contracts:
        - address: nois1a4g7duyu45m0y2ex7s0u8kad87w6ee70v3nz45mh89mjr7zae4pqffrtcz
          code_id: "86"
          git_asset_name: nois_drand
          instantiation_msg: '{"incentive_point_price":"25000","incentive_denom":"unois","min_round":TEMPLATE_MIN_ROUND,"manager":"nois1k40fuuwglguk7ar0g59jv8jtrpv68ptn9vuvp3"}'
          name: nois-drand
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.9.0
        - address: nois1j3des9cjg0adpvkauck6c9muyrw6sxa7keaf82h2taxdjf69z8csw32v0e
          code_id: "87"
          git_asset_name: nois_gateway
          instantiation_msg: '{}'
          name: nois-gateway
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.9.0
        - address: nois1hll7650l8fxmn52ertntghveqn5clr0nwr0j3g3ernxql4qc2vaqqvgs8c
          code_id: "88"
          git_asset_name: nois_icecube
          instantiation_msg: '{"manager":"nois1k40fuuwglguk7ar0g59jv8jtrpv68ptn9vuvp3"}'
          name: nois-icecube
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.9.0
        - address: nois1e07kt078y2aqh2utg9mjjesjlrxwngnz2hp9nngevmpue39w54gqufh2d9
          code_id: "89"
          git_asset_name: nois_sink
          instantiation_msg: '{}'
          name: nois-sink
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.9.0
  - binary_name: aurad
    chain_id: euphoria-2
    denom: ueaura
    faucet: ~
    gas_price: 0.04
    ibc_connection:
      dest: connection-34
      src: connection-22
      counterpart:
        chain: nois-testnet-003
        contract_name: nois-gateway
    name: euphoria-2
    prefix: aura
    rpc:
      - "https://rpc.euphoria.aura.network:443"
    wasm:
      contracts:
        - address: aura1dz64l7pgcm45p3hctydqj7c6gn9czy0mqmst9dh2e0s25q66xumqe3atts
          code_id: "534"
          git_asset_name: nois_proxy
          instantiation_msg: '{"prices":[{"denom":"TEMPLATE_DENOM","amount":"100"}],"withdrawal_address":"TEMPLATE_WITHDRAWAL_ADDRESS","callback_gas_limit":500000,"test_mode":false}'
          name: nois-proxy
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.9.0
        - address: aura1hua8spr4rdd5z429n64xvzkfmyjcanlcqd9vd8jmkz5wmvsrzwdqu9u2ce
          code_id: "535"
          git_asset_name: nois_demo
          instantiation_msg: '{"nois_proxy":"TEMPLATE_NOIS_PROXY"}'
          name: nois-demo
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.9.0
        - address: aura1aq0tyaeqra03cad9ufh0hs7yrqgmkannqf8gsv3yuav2d6954eqsz9r5me
          code_id: "536"
          git_asset_name: double_dice_roll
          instantiation_msg: '{"nois_proxy":"TEMPLATE_NOIS_PROXY"}'
          name: double-dice-roll
          url: "https://github.com/noislabs/nois-dapp-examples"
          version: v0.5.0
  - binary_name: starsd
    chain_id: elgafar-1
    denom: ustars
    faucet: ~
    gas_price: 0.025
    ibc_connection:
      dest: connection-35
      src: connection-134
      counterpart:
        chain: nois-testnet-003
        contract_name: nois-gateway
    name: elgafar-1
    prefix: stars
    rpc:
      - "https://rpc.elgafar-1.stargaze-apis.com:443"
    wasm:
      contracts:
        - address: stars1rwz59llxr8keukmuq0kset62szc0hynneh6csxsqc0gkerh7fznslhklc3
          code_id: "1627"
          git_asset_name: nois_proxy
          instantiation_msg: '{"prices":[{"denom":"TEMPLATE_DENOM","amount":"100"}],"withdrawal_address":"TEMPLATE_WITHDRAWAL_ADDRESS","callback_gas_limit":500000,"test_mode":false}'
          name: nois-proxy
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.9.0
        - address: stars1ajpg2kjh0dqqereasnnxmjhkffctd0kvqc8m2lejj7ud3ff9qqss7as6z3
          code_id: "1628"
          git_asset_name: nois_demo
          instantiation_msg: '{"nois_proxy":"TEMPLATE_NOIS_PROXY"}'
          name: nois-demo
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.9.0
        - address: stars1xpc7ls6zu2h930qwf6ejn32ufncnnuw2snkzh2pcn2nwnfxfey9qtdcsz8
          code_id: "1629"
          git_asset_name: double_dice_roll
          instantiation_msg: '{"nois_proxy":"TEMPLATE_NOIS_PROXY"}'
          name: double-dice-roll
          url: "https://github.com/noislabs/nois-dapp-examples"
          version: v0.5.0
  - binary_name: junod
    chain_id: uni-6
    denom: ujunox
    faucet: "https://faucet.uni.juno.deuslabs.fi"
    gas_price: 0.025
    ibc_connection:
      dest: connection-38
      src: connection-61
      counterpart:
        chain: nois-testnet-003
        contract_name: nois-gateway
    name: uni-6
    prefix: juno
    rpc:
      - "https://rpc.uni.junonetwork.io:443"
    wasm:
      contracts:
        - address: "juno1gz5959mh8xv6s3m8wacwdzz33wr4gk4rphna403rtpc3wyk0rsys4r8uw2"
          code_id: "324"
          git_asset_name: nois_proxy
          instantiation_msg: '{"prices":[{"denom":"TEMPLATE_DENOM","amount":"100"}],"withdrawal_address":"TEMPLATE_WITHDRAWAL_ADDRESS","callback_gas_limit":500000,"test_mode":false}'
          name: nois-proxy
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.9.0
        - address: "juno1rquemycmaz0jvhmlkmvpzc9kfwszsdkxzu4dlufklegqka436a2qj8lwur"
          code_id: "325"
          git_asset_name: nois_demo
          instantiation_msg: '{"nois_proxy":"TEMPLATE_NOIS_PROXY"}'
          name: nois-demo
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.9.0
        - address: juno124dktlf9c7rfm96f69a66z9hvydp8ycfrq86l4frx3v2s9gkmtds2xx4cg
          code_id: "331"
          git_asset_name: double_dice_roll
          instantiation_msg: '{"nois_proxy":"TEMPLATE_NOIS_PROXY"}'
          name: double-dice-roll
          url: "https://github.com/noislabs/nois-dapp-examples"
          version: v0.5.0
  - binary_name: juno1d
    chain_id: juno-1
    denom: ujuno
    faucet: ~
    gas_price: 0.0025
    ibc_connection:
      dest: ~
      src: ~
      counterpart:
        chain: nois-testnet-003
        contract_name: nois-gateway
    name: juno-1
    prefix: juno
    rpc:
      - "https://rpc-juno.mib.tech:443"
    wasm:
      contracts:
        - address: "null"
          code_id: "null"
          git_asset_name: nois_proxy
          instantiation_msg: '{"prices":[{"denom":"TEMPLATE_DENOM","amount":500000}],"withdrawal_address":"TEMPLATE_WITHDRAWAL_ADDRESS","callback_gas_limit":500000,"test_mode":false}'
          name: nois-proxy
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.9.0
        - address: "null"
          code_id: "null"
          git_asset_name: double_dice_roll
          instantiation_msg: '{"nois_proxy":"TEMPLATE_NOIS_PROXY"}'
          name: double-dice-roll
          url: "https://github.com/noislabs/nois-dapp-examples"
          version: v0.5.0
ibc:
  relayer:
    docker_image: noislabs/nois-relayer
  version: nois-v5
